### ISSUE TITLE
Long term support?

### ISSUE THREAD

**Issue by Ezwen** [DanielHuisman/traefik-certificate-extractor#1]
Hi! 

Sorry to ask the question with a Github issue, but I was wondering: do you plan to maintain this script and/or docker image in the long term?

It matches perfectly what I need (monitoring the changes in the `acme.json` file, and dumping everything accordingly), but I might not be able to fix the script if, for instance, traefik changes its file format.

**Comment by DanielleHuisman** [comment]
For the foreseeable future I will continue to maintain this script. If you find any bugs or have a feature request, just create an issue on this repo.

**Comment by Ezwen** [comment]
Great, thanks for answering.
