### ISSUE TITLE
Extract certificates on first run

### ISSUE THREAD

**Issue by riker09** [DanielHuisman/traefik-certificate-extractor#13]
When the script is run for the first time and no certficates have been extracted it should extract them once.

**Comment by andig** [comment]
Not sure I'm seeing the same issue, but running for the first time like this after initial setup seems to do nothing:

    sudo docker run --rm -v $(pwd)/data:/app/data -v $(pwd)/certs:/app/certs danielhuisman/traefik-certificate-extractor

**Comment by andig** [comment]
Ok, got it- need to mount the acme's folder into /app/data:

    admin@NAS:~$ sudo docker run --rm -v /volume1/data/docker/traefik/:/app/data -v $(pwd)/certs:/app/certs danielhuisman/traefik-certificate-extractor

It would still be great if certificates would be extracted on first run as @riker09 wrote.

**Comment by DanielleHuisman** [comment]
Thanks for the suggestion. I haven't been able to update this project lately, due to my lack of spare time. I might look into this in a few days, but feel free to make a PR

**Comment by andig** [comment]
I'm not a python guru but on quick try this works. Can we always assume that the file will be called `acme.json`? Then the event handler might also check for the exact name?
