### ISSUE TITLE
Extract certificates from KV store (not acme.json)

### ISSUE THREAD

**Issue by riker09** [DanielHuisman/traefik-certificate-extractor#14]
When running Traefik in a multi-host environment (read: Docker swarm) it is encouraged (required?) to store the certificates in a KV store. Otherwise you'd have to come up with a clever way to synchronize the acme.json file with all Traefik instances.

The configuration looks like this:

```toml
# File or key used for certificates storage.
#
# Required
#
# storage = "acme.json"
storage = "traefik/acme/account"
```

Judging from the `extractor.py` script this is currently not supported?

**Comment by DanielleHuisman** [comment]
This is not currently supported. I don't have the time to implement it myself at the moment, but feel free to make a PR.

**Comment by andig** [comment]
Here is an open PR for KV support: https://github.com/ldez/traefik-certs-dumper/pull/6. `traefik-certs-dumper` does not support watching though.

**Comment by smueller18** [comment]
Watching is also part of the PR 😉
