### ISSUE TITLE
Fails to startup

### ISSUE THREAD

**Issue by consult-kk** [DanielHuisman/traefik-certificate-extractor#17]
This docker command fails to startup.. any ideas what I am doing wrong here ?
docker run --name extractor -d -v /home/ec2-user/traefik/acme.json:/app/data/acme.json -v /home/ec2-user/traefik/certs:/app/data/certs  -v /var/run/docker.socket:/var/run/docker.sock snowmb/traefik-certificate-extractor -r

the error I get is 
"usage: extractor.py [-h] [-c CERTIFICATE] [-d DIRECTORY] [-f] [-r] [--dry-run]
                    [--include [INCLUDE [INCLUDE ...]] | --exclude
                    [EXCLUDE [EXCLUDE ...]]]
extractor.py: error: argument -d/--directory: path does not exist: 'certs'"

**Comment by andig** [comment]
Imho you need to map to app/certs

Viele Grüße,
Andreas
