### ISSUE TITLE
Evaluate PRs/forks for Traefik v2 support

### ISSUE THREAD

**Issue by DanielleHuisman** [DanielHuisman/traefik-certificate-extractor#23]
Including, but not limited to:
- #19 Traefik 2.1.1 support
- #20 Traefik 2 acme file format compatibility

I personally haven't used this tool in a while, so maintaining this project is a low priority. From what I've seen the PRs/forks mostly introduce CLI flags to support Traefik v2. In my opinion, the tool should automatically detect which Traefik version is being used.

Apparently, there is also a similar project that does support Traefik v2, so those waiting for my project can check it out: https://github.com/ldez/traefik-certs-dumper. I haven't tested it personally, so I can't comment its features.

Ever since starting this project, I've been of the mindset that, at some point in time, Traefik should natively support exporting/accessing certificates instead of using tools like mine. However, I understand that making a Traefik PR takes more work than just installing this simple Python script. I personally don't have the time or need to make a PR to Traefik, but I would highly encourage somebody to do so or at least raise this use case as an issue with Traefik.

**Comment by macwinnie** [comment]
https://hub.docker.com/r/devopsansiblede/acme_certs_extract

Since this feature is still not available on the official images, we've built our own image and re-implemented the whole Certs extract process. Have a look and feel free to use! =)
