### ISSUE TITLE
No arm support!?

### ISSUE THREAD

**Issue by user897943** [DanielHuisman/traefik-certificate-extractor#24]
Please add arm support for this image, I want to run it on Raspberry Pi 4, thanks in advance.

**Comment by DanielHuisman** [comment]
It is a Python script? Should run just fine on ARM.

**Comment by user897943** [comment]
I'm talking about the docker image. It was built for amd_64/x86 platform therefore it does not run on ARM/Raspberry Pi. This is what I am referring to. Thanks
